### PR TITLE
Improve Ractor-compliance

### PR DESCRIPTION
**Pull request by rm155**
By freezing constants, ipaddr can improve its ability to be used in Ractors.

### CODE REVIEW

**Review by ioquatix — APPROVED** [review]

**Comment by ioquatix** [comment]
Can you check why this is failing and propose a fix?

**Comment by hsbt** [comment]
@rm155 Can you describe why you remove the `assert_warning`?

**Comment by rm155** [comment]
> @rm155 Can you describe why you remove the `assert_warning`?

When ioquatix asked me to check why the pull request was failing, I found that the error was "undefined method `assert_warning'". Removing the assert_warning seemed to fix it. But I'm not sure if there was a better solution.

**Comment by hsbt** [comment]
I see. The current HEAD is passed with `assert_warning`. I'll merge this.

**Comment by hsbt** [comment]
Merged at https://github.com/ruby/ipaddr/commit/73461724e5cfbe4e23d7ea6262405f472e643c96

**Pull request closed without merging**
